"""add_location_coordinates

Revision ID: 392faceaa205
Revises: 
Create Date: 2026-05-02 05:24:42.096702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392faceaa205'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification_history', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('classification_history', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classification_history', 'longitude')
    op.drop_column('classification_history', 'latitude')
    # ### end Alembic commands ###
